version: 1.0.{build}  
image: Visual Studio 2017
configuration: Release

before_build:
  -  dotnet restore AWS.API.sln
build:  
  project: src\Services\Amazon.API\Amazon.API
  project: src\Web Apps\AWS.WEB\AWS.WEB
  verbosity: minimal
test: off  
artifacts:  
- path: x64/Release/myfavoriteproject.exe
  name: Release

