version: 1.0.{build}  
image: Visual Studio 2017
configuration: Release

before_build:
  -  dotnet restore AWS.API.sln
build_script:  
  - dotnet build "AWS.API.sln"
  - dotnet build "src\Web Apps\AWS.WEB\AWS.WEB"
test: off  
artifacts:  
- path: x64/Release/myfavoriteproject.exe
  name: Release

