version: 1.0.{build}  
image: Visual Studio 2017
configuration: Release
install:
- choco install docker-compose
build_script:
- ps: & 'C:\Program Files\Docker\Docker\DockerCli.exe' -SwitchDaemon

before_build:
  -  dotnet --info
  -  dotnet restore AWS.API.sln
build:  
  project: AWS.API.sln
  verbosity: minimal
test: off  
artifacts:  
- path: x64/Release/myfavoriteproject.exe
  name: Release

